# see https://medium.com/bb-tutorials-and-thoughts/building-ci-cd-for-react-static-web-apps-service-using-azure-devops-efef72e3772

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

# Download .env file from secure files
# Contains database connection string and iron-session secret
  - task: DownloadSecureFile@1
    inputs:
      secureFile: '.env'

# Copy .env file to artifacts folder
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: '.env'
      targetFolder: '$(System.DefaultWorkingDirectory)'

# Do Azure Web App stuff
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      output_location: '.next'
      azure_static_web_apps_api_token: $(deployment_token)