BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[story] ALTER COLUMN [description_swedish] NVARCHAR(4000) NULL;
ALTER TABLE [dbo].[story] ALTER COLUMN [description_english] NVARCHAR(4000) NULL;
ALTER TABLE [dbo].[story] ALTER COLUMN [open_data] NVARCHAR(4000) NULL;
ALTER TABLE [dbo].[story] ALTER COLUMN [reports] NVARCHAR(4000) NULL;
ALTER TABLE [dbo].[story] ALTER COLUMN [videos] NVARCHAR(4000) NULL;
ALTER TABLE [dbo].[story] ALTER COLUMN [pdf_case] NVARCHAR(4000) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
