name: Upload Production Code (AGPL)



on:
  push:
    branches:
      - main

concurrency:
  group: upload-prod-code-${{ github.ref}}
  cancel-in-progress: true

jobs:
  upload-zip:
    name: Upload Production Dependencies
    runs-on: ubuntu-latest
    env:
      OUTPUT: production-dependencies.zip
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --omit=dev
      - name: Upload production dependencies
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT }}
          # react-leaflet is licensed under Hippocratic-2.1, which is not compatible with AGPL-3.0 and therefore must be excluded since we're technically relicensing the included dependencies under AGPL-3.0.
          path: |
            node_modules
            !node_modules/@react-leaflet
            !node_modules/react-leaflet
          compression-level: 9
          retention-days: 5

  update-live-release:
    name: Update Live Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: upload-zip
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ZIP_NAME: production-dependencies.zip
    steps:
      - uses: actions/checkout@v4
      - name: Install github-release
        run: |
          go install github.com/github-release/github-release@latest
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Set environment variables
        run: |
          echo "GITHUB_USER=$( echo ${{ github.repository }} | cut -d/ -f1 )" >> $GITHUB_ENV
          echo "GITHUB_REPO=$( echo ${{ github.repository }} | cut -d/ -f2 )" >> $GITHUB_ENV
      - name: Move/Create live tag
        run: |
          git tag --force live ${{ github.sha }}
          git push --tags --force
      - name: Setup live release
        run: |
          DESCRIPTION="Triggered on $(date -u '+%Y/%m/%d, %H:%M') UTC by commit ${{ github.sha }} (@${{ github.actor }})
          This is an automated collection of the production dependencies and source code for the project. It does not include the dependency react-leaflet, as it is licensed under Hippocratic-2.1, which is not compatible with AGPL-3.0.
          The collection of dependencies is included to comply with the license of the project, but for actual usage it is recommended to install the dependencies via npm or another package manager, especially since this collection doesn't include dev dependencies or react-leaflet.
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          if ! github-release info -t live > /dev/null 2>&1; then
            github-release release \
              --tag live \
              --name "Live Build" \
              --description "$DESCRIPTION" \
          else
            github-release edit \
              --tag live \
              --name "Live Build" \
              --description "$DESCRIPTION" \
          fi
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: ${{ env.ZIP_NAME }}
      - name: Add artifact to release
        run: |
          github-release upload \
            --tag continuous \
            --replace \
            --name ${{ env.ZIP_NAME }} \
            --file ${{ env.ZIP_NAME }}/${{ env.ZIP_NAME }}